site_name: ChemGraphBuilder
nav:
  - Home: index.md
  - Usage_Examples:
    - Step1_NodesCollectorProcessor: 1.node_collector_processor.md
    - Class_Documentation: node_collector_processor.md
    - Step2_RelationshipCollectorProcessor: 2.relationship_collector_processor.md
    - Class_Documentation: relationship_collector_processor.md
    - Step3_GraphNodesLoader: 3.graph_nodes_loader.md
    - Class_Documentation: graph_nodes_loader.md
    - Step4_GraphRelationshipsLoader: 4.graph_relationships_loader.md
    - Class_Documentation: graph_relationships_loader.md
  - Documentation: documentation.md
  - About: about.md

theme: "material"

plugins:
  - mkdocstrings
  
extra_css:
  - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.3.1.slim.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js
  - https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js
